 trigger:
 - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  BuildProjects: '**/*.csproj'
  Testprojects: '**/*[Tt]ests/*.csproj'  
  Version.MajorMinor: 1.0
  Version.Revision: $[counter(variables['Version.MajorMinor'], 0)]]
  Project.Author: 'diegosmorf'
  Project.Name: 'AmberEggApi'

steps:
- task: Assembly-Info-NetCore@2
  displayName: 'Assembly Info'
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: $(BuildProjects)
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    PackageId: '$(Build.SourceBranchName)'
    Authors: '$(Project.Author)'
    Company: '$(Project.Name)'
    Product: '$(Project.Name)'
    Description: '$(Project.Name)'
    Copyright: '$(Project.Name)'        
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'normal'
    FailOnWarning: false
    DisableTelemetry: false

- task: SonarCloudPrepare@1
  displayName: 'Sonarcloud Prepare'
  inputs:
    SonarCloud: 'SonarCloud.AmberEggApi'
    organization: '$(Project.Author)'
    scannerMode: 'MSBuild'
    projectKey: '$(Project.Name)'
    projectName: '$(Project.Name)'
    extraProperties: |     
     sonar.exclusions=**/obj/**,**/*.dll
     sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml
     sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx

- task: DotNetCoreCLI@2
  displayName: 'DotNetCore Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: $(BuildProjects)
    vstsFeed: 'e515f851-a794-40b2-a603-30214ed962ae/a86b4459-e784-456a-af3b-bd0dec42c1ce'
    verbosityRestore: 'Minimal'

- task: DotNetCoreCLI@2
  displayName: 'DotNetCore Build'  
  inputs:
    projects: $(BuildProjects)
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'DotNetCore Test'  
  inputs:
    command: test
    projects: $(Testprojects)
    arguments: '--configuration $(BuildConfiguration) --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx'

- task: DeleteFiles@1
  displayName: 'Delete files from $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: |
     **/*.pdb
     **/cs
     **/da
     **/de
     **/es
     **/fa
     **/fi
     **/fr
     **/it
     **/nl
     **/pl
     **/pt
     **/ru
     **/sv
     **/zh-cn
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: SonarCloudAnalyze@1
  displayName: 'Sonarcloud Analyze'

- task: SonarCloudPublish@1
  displayName: 'Sonarcloud Publish'
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'DotNetCore Publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*WebApi*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-build'
    zipAfterPublish: True
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))