name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore 
      working-directory: ./src


      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src
    
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        projectKey: AmberEggApi
        projectName: AmberEggApi
        buildCommand: dotnet build src/.
        sonarOrganisation: julioarruda
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
            /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
      working-directory: ./src

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: ${{ github.workspace }}/out
